# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'przegladanie.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import przegladanie
import os

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 20, 211, 31))
        self.label.setStyleSheet("QLabel{\n"
"background-color: rgb(75, 255, 249);\n"
"}\n"
"QLabel:hover{\n"
"background-color: rgb(75, 255, 249);\n"
"border: 2px solid rgb(255,0,0);\n"
"font-size:16px;\n"
"}\n"
"")
        self.label.setObjectName("label")

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 251, 31))
        self.label_2.setStyleSheet("QLabel{\n"
"background-color: rgb(75, 255, 249);\n"
"}\n"
"QLabel:hover{\n"
"background-color: rgb(75, 255, 249);\n"
"border: 2px solid rgb(255,0,0);\n"
"font-size:16px;\n"
"}\n"
"")
        self.label_2.setObjectName("label_2")

        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(38, 120, 431, 31))
        self.comboBox.setStyleSheet("QComboBox{\n"
"background-color: rgb(75, 255, 249);\n"
"}\n"
"QComboBox:hover{\n"
"background-color: rgb(75, 255, 249);\n"
"border: 2px solid rgb(255,0,0);\n"
"font-size:16px;\n"
"}\n"
"")
        self.comboBox.setObjectName("comboBox")

        self.combo(  )
        # self.comboBox.addItems( przegladanie.folder( os.getcwd()) )

        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget,
                                                  clicked=lambda: self.przejdz_do_folderu(self.comboBox.currentText()))
        self.pushButton_3.setGeometry(QtCore.QRect(490, 120, 150, 41))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
                                        "    text-decoration: underline;\n"
                                        "    font: 75 8pt \"MS Shell Dlg 2\";\n"
                                        "background-color: rgb(75, 255, 249);\n"
                                        "font-size: 18px;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "background-color: rgb(255, 25, 29);\n"
                                        "border: 2px solid rgb(255,0,0);\n"
                                        "font-size: 20px;\n"
                                        "}\n"
                                        "")
        self.pushButton_3.setObjectName("pushButton_3")

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda : self.pokaz1( self.comboBox.currentText()))
        self.pushButton_2.setGeometry(QtCore.QRect(490, 180, 150, 41))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    text-decoration: underline;\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(75, 255, 249);\n"
"font-size: 18px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 25, 29);\n"
"border: 2px solid rgb(255,0,0);\n"
"font-size: 20px;\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")

        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(40, 170, 431, 301))
        self.textBrowser.setStyleSheet("QTextBrowser{\n"
"background-color: rgb(208, 208, 208)\n"
"}\n"
"QTextBrowser:hover{\n"
"background-color: rgb(178, 178, 178);\n"
"border: 2px solid rgb(255,0,0);\n"
"}\n"
"")
        self.textBrowser.setObjectName("textBrowser")

        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(490, 230, 91, 41))
        self.lcdNumber.setStyleSheet("QLCDNumber{\n"
"background-color: rgb(75, 255, 249);\n"
"}\n"
"QLCDNumber:hover{\n"
"background-color: rgb(75, 255, 249);\n"
"border: 2px solid rgb(255,0,0);\n"
"}\n"
"")
        self.lcdNumber.setObjectName("lcdNumber")


        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_2.setGeometry(QtCore.QRect(490, 290, 91, 41))
        self.lcdNumber_2.setStyleSheet("QLCDNumber{\n"
"background-color: rgb(75, 255, 249);\n"
"}\n"
"QLCDNumber:hover{\n"
"background-color: rgb(75, 255, 249);\n"
"border: 2px solid rgb(255,0,0);\n"
"}\n"
"")
        self.lcdNumber_2.setObjectName("lcdNumber_2")

        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_3.setGeometry(QtCore.QRect(490, 350, 91, 41))
        self.lcdNumber_3.setStyleSheet("QLCDNumber{\n"
"background-color: rgb(75, 255, 249);\n"
"}\n"
"QLCDNumber:hover{\n"
"background-color: rgb(75, 255, 249);\n"
"border: 2px solid rgb(255,0,0);\n"
"}\n"
"")
        self.lcdNumber_3.setObjectName("lcdNumber_3")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(490, 410, 131, 41))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    text-decoration: underline;\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(75, 255, 249);\n"
"font-size: 18px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 25, 29);\n"
"border: 2px solid rgb(255,0,0);\n"
"font-size: 22px;\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def combo(self, sciezka = os.getcwd() ):
        print( 'combo ', sciezka , os.getcwd() )
        return self.comboBox.addItems( przegladanie.folder(sciezka)[0])

    def pokaz1(self, pressed ): # NIE PRZEKAZUJE CALEJ SCIEZKI !!!!!!!
        # self.textBrowser.setText( self.comboBox.currentText() )
        # self.textBrowser.setText( przegladanie.trescfolderu(self.comboBox.currentText()))
        if os.path.isdir( self.comboBox.currentText() ): # NIE DZIALA LCD DLA FOLDERO
            print( self.comboBox.currentText() , pressed  )
            self.textBrowser.setText(przegladanie.trescfolderu(self.comboBox.currentText()))
            # print( przegladanie.policz_foldery( os.path.join(os.getcwd(),self.comboBox.currentText() )))
            self.lcdNumber_2.display(przegladanie.policz_pliki( self.comboBox.currentText() ))
            # print( os.path.join(os.getcwd() ,self.comboBox.currentText()))

        else:
            self.textBrowser.setText( przegladanie.trescpliku(self.comboBox.currentText()))

    # def lista_folderow(self, sciezka ):
    #     return przegladanie.folder(sciezka)[0]

    def gdzie_jestem(self, sciezka = os.getcwd()):
        return sciezka 

    def przejdz_do_folderu(self,pressed ):

        if os.path.isdir( self.comboBox.currentText() ) and pressed == '.\\':
            print( 'wyzej ', pressed )
        if os.path.isdir( self.comboBox.currentText() ):
            gdzie = os.getcwd()
            gdzie2 = os.path.abspath(pressed)
            do_srodka = os.path.join( gdzie , pressed)
            print( 1, gdzie, do_srodka,' -- ',gdzie2 )
            os.chdir( do_srodka )
            gdzie = os.getcwd()
            print(2, gdzie,3 )
            self.combo( gdzie )
        #     print( self.gdzie_jestem( gdzie))
        #     print( przegladanie.folder( gdzie ), pressed , gdzie )
        #     self.comboBox.addItems( przegladanie.folder( gdzie ))

            # self.pokaz1( os.getcwd() )
            # foldery = gdzie.split( os.sep )
            # print(3, foldery )
            # wyzej =  "\\".join( foldery[:-1])
            # print(4, wyzej )
            # print( os.getcwd() )

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "przegladamy wybrane foldery"))
        self.label_2.setText(_translate("MainWindow", "poniżej wybierz do którego folderu zajrzeć"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_2.setText(_translate("MainWindow", "Pokaż zawartość"))
        self.pushButton_3.setText(_translate("MainWindow", "Przejdź do folderu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
